### ISSUE TITLE
Problem to make a shop

### ISSUE THREAD

**Issue by DorianBranquet** [Blackixx/BossShopPro#1]
Hey, I've a problem with your plugin bossshoppro, when I create a shop i make a lot of item but its become stone, if you can help  me please. 
my shop:
https://pastebin.com/YBqqAjmM
Screen:
http://www.noelshack.com/2019-11-4-1552591351-2019-03-14-20-15-22.png
Thanks.

**Comment by Blackixx** [comment]
Hey,
what BSP and what Spigot version do you use?

If you use Spigot 1.13 and above I suggest using material names instead of ids.
