### ISSUE TITLE
API Question: Is it possible to listen to new transactions?

### ISSUE THREAD

**Issue by vacoup95** [Blackixx/BossShopPro#103]
I would like to create an addon that listens to transactions (buy and sell) I couldn't find it in the docs nor the in the API code. Is it currently possible to do this? If so, can you point me in the right direction?

My goal is to create an addon for BossShop that logs all transactions to MySQL.

Thanks in advance!

**Comment by Blackixx** [comment]
Take a look at the following event to which you can listen:
https://github.com/Blackixx/BossShopPro/blob/master/src/main/java/org/black_ixx/bossshop/events/BSPlayerPurchasedEvent.java
(check out the event package for more events)

**Comment by vacoup95** [comment]
> Take a look at the following event to which you can listen:
> https://github.com/Blackixx/BossShopPro/blob/master/src/main/java/org/black_ixx/bossshop/events/BSPlayerPurchasedEvent.java
> (check out the event package for more events)

Thank you
