### ISSUE TITLE
Organizing Into Folders 

### ISSUE THREAD

**Issue by BobbyMere** [Blackixx/BossShopPro#104]
I understand that you've mostly abandoned this plugin and only updating it because you're such a nice person, and you've realized that this plugin is far superior to all others. And to this, I thank you. 

My question is, can you please update it so you can store <shops>.yml's into folders so it's not an endless list of .ymls, please?

**Comment by Blackixx** [comment]
Already possible.

Check out the following config option:
`# SearchSubfoldersForShops:
# If enabled BossShop will search children folders of the '/shops' directory for shop files. That can be quite helpful for sorting, when dealing with a big amount of shops.
SearchSubfoldersForShops: false`

**Comment by BobbyMere** [comment]
I've been using this for years and I had no idea. When was this added?
