### ISSUE TITLE
[QUESTION] Project license

### ISSUE THREAD

**Issue by Nikox3003** [Blackixx/BossShopPro#109]
Hi, I want to ask question about project license. Can I modify the code (for example add support to my private points plugin) and use it on my own server? I know that project is now open source, however there isn't a license file in repository. Default license prohibits any use of modified code ([click for more details](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository)).

**Comment by JJCprodeveloper** [comment]
Just use it lmao 
this plugin is dead,also nobody would know you are using a modified version as long as you do not distribute it

**Comment by Blackixx** [comment]
You can use it. Also, I will add a license to it today, allowing anyone to change and distribute the code. Plus If I have enough time, I’ll reply to the spigot thread and give some updates.
