### ISSUE TITLE
bossshoppro bug

### ISSUE THREAD

**Issue by geumu** [Blackixx/BossShopPro#17]
i found bug
https://youtu.be/L4elOpGL8_k

iam using bossshoppro and bskyblock
when i make GUI with bossshoppro
bossshop menu -> /is top -> You can subtract items from the GUI.
but when i just use /is top
i can not subtract items from the GUI.

**Comment by geumu** [comment]
that is 1.13.2 paperspigot

**Comment by Blackixx** [comment]
https://www.spigotmc.org/wiki/bossshoppro-faq-and-help/ -> "My players are able to take items out of the GUI": DId you check this out already?
