### ISSUE TITLE
Condition Results

### ISSUE THREAD

**Issue by mibby** [Blackixx/BossShopPro#41]
@Blackixx Would it be possible to add an option for condition results instead of just hiding or showing the item? 

For example, I'm trying to build out an unlock system GUI. I'd like to display all possible unlocks in each category but as red glass pane when you don't have permission. If users have permission for that item (i.e. unlocked), the GUI icon slot becomes that item instead. 

As far as I know, this is not possible in BossShopPro. Setting permission requirements just hides items instead of displaying them as locked. Instead of having it so items are hidden when condition results returning false, it would be nice to have an option to display something else.

**Comment by Blackixx** [comment]
What you want to achieve is already possible: You can assign the same inventory slot to multiple items. Always the first item will be shown, except it is hidden, then the next item is shown.

**Comment by mibby** [comment]
@Blackixx That's not what I want though. I want _all_ items to display and be shown as a red glass pane when users do not have permission to access it. If they do have permission, it shows the actual item and allows them to click on it to run the associated commands.

I do not want any items to be hidden.

**Comment by mibby** [comment]
@Blackixx Is this not going to be something ever possible then? :(

**Comment by Blackixx** [comment]
This is possible using the way I (admittedly very shortly) described. If a user does not have permissions for an item, you can hide the item and instead show the very same item (another item in config but same properties) but just looking like a glass pane and having RewardType none and Pricetype none, aswell as Message something like "Not unlocked yet".

**Comment by mibby** [comment]
Ah, I see what you mean. Basically I'd need to duplicate every entry and no longer use arbitrary inventory location slots (0). I suppose that can work, thanks. 

Just a bit tedious since it requires copying hundreds of items, giving everything a different internal name, removing the permission conditions on the new ones, and adding a matching slot ID for the original and clone.
