### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by Ant4rez** [Blackixx/BossShopPro#47]
Log:
https://paste.ubuntu.com/p/z5WKnF6tdP/

Server: Paper version git-Paper-238 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Plugins: AuthMe, BossShopPro, CoreProtect, DeluxeCombat, Essentials, EssentialsChat, EssentialsSpawn, ezAuctions, FastLogin, GemsEconomy*, IllegalStack, JupiterCore, LuckPerms, Matrix, mcMMO, Minepacks, MoneyHunters, MysqlEconomyBank, OpGuard*, PlaceholderAPI, PlayerShops, ProtectionStones, ProtocolLib, React*, SkinsRestorer, TitleManager*, UltimateCatcher, UltimateStacker, Vault, ViaVersion*, WorldBorder, WorldEdit, WorldGuard, Zenchantments

**Comment by Logende** [comment]
was fixed
