### ISSUE TITLE
More custom symbols

### ISSUE THREAD

**Issue by madtomic** [Blackixx/BossShopPro#61]
[tools] -> ⚒
[swords] -> ⚔

How can I add more of these?

**Comment by Blackixx** [comment]
What is your concrete goal? 

As user of BossShopPro (server admin) you can already add any unicode symbol to your shop configuration files. Those symbol shortcuts/placeholders are not needed, actually. BSP includes them simply to make things easier for server admins. More info about symbols: https://www.spigotmc.org/wiki/bossshoppro-placeholders/

As developer working with the source code of BossShopPro, you can add new symbol placeholders here: https://github.com/Blackixx/BossShopPro/blob/master/src/main/java/org/black_ixx/bossshop/managers/misc/StringManager.java
