### ISSUE TITLE
Custom skulls not displaying in 1.16.1 Spigot

### ISSUE THREAD

**Issue by PixNyb** [Blackixx/BossShopPro#74]
After upgrading my server and the plugin to the latest builds (from 1.15.2 to 1.16.1) custom playerheads in the gui will just display the default steve head instead of the value they should have.

Config:
`  bees:
    MenuItem:
    - "lore:&7It's an unfortunate way to die."
    - name:&8- &eNot the bees!
    - amount:1
    - type:PLAYER_HEAD
    - customskull:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTQwMDIyM2YxZmE1NDc0MWQ0MjFkN2U4MDQ2NDA5ZDVmM2UxNWM3ZjQzNjRiMWI3Mzk5NDAyMDhmM2I2ODZkNCJ9fX0=
    RewardType: NOTHING
    PriceType: NOTHING
    Message: '&8| &7R.I.P.'
    ExtraPermission: 'aums.achievements.bees'
    InventoryLocation: 9`

Result:
![image](https://user-images.githubusercontent.com/40770831/86449175-15278e00-bd18-11ea-8b0b-58b45b266e5f.png)

**Comment by Ant4rez** [comment]
I don't have problems with custom skull, use it like this:

`    MenuItem:
    - type:PLAYER_HEAD:3
    - customskull:'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWJiODRlMzQ4YWI1OGJlMDQzNWY2MWUwMjdmYTZkZmU1NTdiZWU4ODkzZjFjMTBjM2MyYmViZDIwMjVkYSJ9fX0='`
